[versions]
# Kotlin
kotlin = "1.9.25"

# Android
android-gradle = "8.2.0"

# Compose
compose-bom = "2024.02.00"
compose-compiler = "1.5.15"

# AndroidX
androidx-core = "1.12.0"
androidx-lifecycle = "2.7.0"
androidx-activity-compose = "1.8.2"
androidx-navigation = "2.7.7"

# Testing
junit = "4.13.2"
androidx-test-junit = "1.1.5"
androidx-test-espresso = "3.5.1"

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
