[versions]
# Kotlin
kotlin = "1.9.25"
kotlinx-coroutines = "1.8.0"
kotlinx-serialization = "1.6.3"

# Android
android-gradle = "8.2.0"
androidx-core = "1.12.0"

# Compose
compose-bom = "2024.02.00"
compose-compiler = "1.5.15"

# Testing
junit = "4.13.2"
androidx-test-junit = "1.1.5"
androidx-test-espresso = "3.5.1"

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "android-gradle" }
